FROM debian:stretch-slim
MAINTAINER Simon Martin <havvoric@gmail.com>

RUN apt-get update && \
    apt-get install -y --no-install-recommends cclive ca-certificates && \
    rm -rf /var/lib/apt/lists/*


